version: "2"
services:
  detectron:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPOSE_PORT=${EXPOSE_PORT}
        - APPLICATION_PORT=${APPLICATION_PORT}
    ports:
      - ${EXPOSE_PORT}:${APPLICATION_PORT}
    image: slim/detectron2
    container_name: detectron2
