version: "2"
services:
  detectron:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - EXPOSE_PORT=${EXPOSE_PORT}
    ports:
      - 8080:5000
    image: slim/detectron2
    container_name: detectron2
